DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS students_courses;

CREATE SCHEMA school;

CREATE TABLE school.courses
(
    course_id integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    course_name varchar(255) NOT NULL,
    course_description varchar(255) NOT NULL,
    CONSTRAINT courses_pkey PRIMARY KEY (course_id)
);
       

CREATE TABLE school.groups
(
    group_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    group_name varchar(255) NOT NULL,
    CONSTRAINT groups_pkey PRIMARY KEY (group_id)
);
    

CREATE TABLE school.students
(
    student_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    group_id integer NULL,
    first_name varchar(255) NOT NULL,
    last_name varchar(255) NOT NULL,
    CONSTRAINT students_pkey PRIMARY KEY (student_id),
    CONSTRAINT students_groupid_fkey FOREIGN KEY (group_id)
        REFERENCES school.groups (group_id)
        ON DELETE RESTRICT
);
    

CREATE TABLE school.students_courses
(
	student_id integer NOT NULL,
	course_id integer NOT NULL,
	CONSTRAINT students_and_courses_pkey PRIMARY KEY (student_id, course_id),
	CONSTRAINT students_courses_fkey FOREIGN KEY (student_id)
		REFERENCES school.students (student_id)
		ON DELETE CASCADE,
	CONSTRAINT students_courses_fkey2 FOREIGN KEY (course_id)
		REFERENCES school.courses (course_id)
		ON DELETE CASCADE
);